In [1]:
import pandas as pd
import numpy as np

In [2]:
x = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9],],
 [[11,12,13], [14,15,16], [17,18,19],],
 [[21,22,23], [24,25,26], [27,28,29]]])
x.shape

(3, 3, 3)

# Slicing 

In [3]:
print(x)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


- Slicing rows

In [4]:
x[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
x[1]

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [6]:
x[0][2]

array([7, 8, 9])

In [7]:
x[0][2][0]

7

- Slicing columns

In [8]:
x = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9],],
 [[11,12,13], [14,15,16], [17,18,19],],
 [[21,22,23], [24,25,26], [27,28,29]]])
x.shape

(3, 3, 3)

In [10]:
x

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [9]:
x[:,1]

array([[ 4,  5,  6],
       [14, 15, 16],
       [24, 25, 26]])

- Dicing

In [11]:
x[1,1]

array([14, 15, 16])

In [12]:
x[:,1,1]

array([ 5, 15, 25])

In [13]:
x[1,:,1]

array([12, 15, 18])

In [14]:
x[1:2, 1:2]

array([[[14, 15, 16]]])

In [15]:
x[0:2, 0:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

# Concatenating and Transforming

- Adding new cases and variables



In [16]:
import pandas as pd
df = pd.DataFrame({'A': [2,3,1],
 'B': [1,2,3],
 'C': [5,3,4]})
df1 = pd.DataFrame({'A': [4],
 'B': [4],
 'C': [4]})
df 

A  B  C
0  2  1  5
1  3  2  3
2  1  3  4

In [17]:
df1

A  B  C
0  4  4  4

In [18]:
df.append?

In [19]:
df.append(df1)

A  B  C
0  2  1  5
1  3  2  3
2  1  3  4
0  4  4  4

In [20]:
df

A  B  C
0  2  1  5
1  3  2  3
2  1  3  4

In [21]:
df = df.append(df1)
df

A  B  C
0  2  1  5
1  3  2  3
2  1  3  4
0  4  4  4

- Removing data

In [23]:
df = pd.DataFrame({'A': [2,3,1],
 'B': [1,2,3],
 'C': [5,3,4]})


In [30]:
df.drop?

In [24]:
df

A  B  C
0  2  1  5
1  3  2  3
2  1  3  4

In [25]:
df = df.drop(df.index[[1]])
df

A  B  C
0  2  1  5
2  1  3  4

In [26]:
df = pd.DataFrame({'A': [2,3,1],
 'B': [1,2,3],
 'C': [5,3,4]})
df


A  B  C
0  2  1  5
1  3  2  3
2  1  3  4

In [27]:
df = df.drop('B', 1)

In [28]:
df

A  C
0  2  5
1  3  3
2  1  4

# Sorting and shuffling

In [31]:
df = pd.DataFrame({
    'col1': ['A', 'A', 'B', np.nan, 'D', 'C'],
    'col2': [2, 1, 9, 8, 7, 4],
    'col3': [0, 1, 9, 4, 2, 3],
    'col4': ['a', 'B', 'c', 'D', 'e', 'F']
})


In [32]:
df

col1  col2  col3 col4
0    A     2     0    a
1    A     1     1    B
2    B     9     9    c
3  NaN     8     4    D
4    D     7     2    e
5    C     4     3    F

In [34]:
df.sort_values?

- Sort by col1

In [35]:
df.sort_values(by=['col1'])

col1  col2  col3 col4
0    A     2     0    a
1    A     1     1    B
2    B     9     9    c
5    C     4     3    F
4    D     7     2    e
3  NaN     8     4    D

In [36]:
df.sort_values(by=['col2'])

col1  col2  col3 col4
1    A     1     1    B
0    A     2     0    a
5    C     4     3    F
4    D     7     2    e
3  NaN     8     4    D
2    B     9     9    c

In [ ]:
df

- Sort by multiple columns

In [37]:
df.sort_values(by=['col1', 'col2'])

col1  col2  col3 col4
1    A     1     1    B
0    A     2     0    a
2    B     9     9    c
5    C     4     3    F
4    D     7     2    e
3  NaN     8     4    D

In [38]:
df1 = pd.DataFrame({
    'col1': ['A', 'A', 'B', np.nan, 'D', 'C'],
    'col2': [2, 1, 9, 8, 7, 4],
    'col3': [0, 1, 9, 4, 2, 3],
    'col4': ['A', 'B', 'C', 'D', 'E', 'F']
})

In [39]:
df1

col1  col2  col3 col4
0    A     2     0    A
1    A     1     1    B
2    B     9     9    C
3  NaN     8     4    D
4    D     7     2    E
5    C     4     3    F

In [41]:
df1.sort_values(by=['col1', 'col4'])

col1  col2  col3 col4
0    A     2     0    A
1    A     1     1    B
2    B     9     9    C
5    C     4     3    F
4    D     7     2    E
3  NaN     8     4    D

- Sort Descending

In [42]:
df.sort_values(by='col1', ascending=False)

col1  col2  col3 col4
4    D     7     2    e
5    C     4     3    F
2    B     9     9    c
0    A     2     0    a
1    A     1     1    B
3  NaN     8     4    D

- Putting NAs first



In [43]:
df.sort_values(by='col1', ascending=False, na_position='first')

col1  col2  col3 col4
3  NaN     8     4    D
4    D     7     2    e
5    C     4     3    F
2    B     9     9    c
0    A     2     0    a
1    A     1     1    B

# Aggregating Data at Any Level

In [44]:
df = pd.DataFrame([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [np.nan, np.nan, np.nan]],
                  columns=['A', 'B', 'C'])

In [45]:
df

A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0
3  NaN  NaN  NaN

- Aggregate these functions over the rows.

In [46]:
df.agg(['sum', 'min'])


A     B     C
sum  12.0  15.0  18.0
min   1.0   2.0   3.0

In [50]:
df.agg?

- Different aggregations per column.

In [47]:
df.agg({'A' : ['sum', 'min'], 'B' : ['min', 'max']})

A    B
max   NaN  8.0
min   1.0  2.0
sum  12.0  NaN

- Aggregate over the columns

In [48]:
df.agg("mean", axis="columns")

0    2.0
1    5.0
2    8.0
3    NaN
dtype: float64

In [49]:
df.agg("sum", axis="columns")

0     6.0
1    15.0
2    24.0
3     0.0
dtype: float64